
#===== Makefile.config =======================================================80
#
#                          State-Space-Explorer.Config
#
# author: 	Susanne van den Elsen
# date: 	2015
#
# Default settings should be overridden when non-default project setup is
# used.
#
#===============================================================================

#===== Variables =============================================================80
#
# Defined here:
# 	DIR		: Directory containing input programs.
#  	BUILD	       	: Directory where state-space-explorer should be build.
#   	RECORD_REPLAY 	: Root directory of subproject record-replay.
#   	UTILS	      	: Root directory of subproject cpp-utils.
#   	CXX
#   	LD
#
#===============================================================================

DIR			:= ../multithreaded-c
BUILD			:= ./build
RECORD_REPLAY	    	:= ../record-replay
UTILS			:= ../cpp-utils
CXX			:= g++
CPPFLAGS		:=
CXXFLAGS		:=
LD			:= g++
LDFLAGS			:= 
